[workspace]
resolver = "3"
members = ["src-tauri", "llminxsolver-rs"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91.1"
license = "MIT"
repository = "https://github.com/Sevilze/llminxsolver-trs"
